name: edgar-research
channels:
  - conda-forge
  - pytorch
  - nvidia/label/cuda-11.8.0 # Specify CUDA channel for PyTorch with GPU support
dependencies:
  - python=3.11
  - pandas>=2.2.2,<3.0.0
  - numpy>=1.26.4,<2.0.0
  - boto3>=1.38.3,<2.0.0
  - transformers>=4.38.0,<5.0.0
  - datasets>=2.17.0,<3.0.0
  - wandb>=0.16.0,<1.0.0
  - pytorch=2.1.0 # Specify version from pyproject.toml
  - torchvision=0.16.0 # Add torchvision, often needed with pytorch
  - torchaudio=2.1.0 # Add torchaudio, often needed with pytorch
  - peft=0.15.0 # Specify version from pyproject.toml
  - cudatoolkit=11.8 # Specify CUDA version for compatibility
  - pip
    # Any additional pip-only dependencies can go here if needed
