on: [push]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry and export plugin
        run: pip install poetry poetry-plugin-export
      - name: Install dependencies
        run: poetry install --no-root
      - name: Run tests
        run: poetry run pytest -q
      - name: Build Lambda package
        run: make lambda-package
      - name: Upload Lambda package artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: EDGAR-Edge/lambda_ingest.zip
      - name: Set up Terraform 
        uses: hashicorp/setup-terraform@v3
      - name: Check Terraform format
        run: terraform -chdir=infra fmt -check

  deploy:
    needs: test-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry and export plugin
        run: pip install poetry poetry-plugin-export
      - name: Install dependencies
        run: poetry install --no-root
      - name: Download Lambda package artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-package
          path: EDGAR-Edge/
      - name: Build Lambda package
        run: make lambda-package
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # Or hardcode your region e.g., us-east-1
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform -chdir=infra init
      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve
